### ISSUE TITLE
No module named sohei

### ISSUE THREAD

**Issue by d3vsid-sudo** [GatewayDiscord/sohei#10]
- Installed requirements

**Error** 👇

![image](https://user-images.githubusercontent.com/64628456/108469641-a3a04e00-72ae-11eb-8714-f9fb96d6c8ab.png)

**Comment by 0x0elliot** [comment]
weird. let me look into it.

**Comment by 0x0elliot** [comment]
@d3vsid-sudo would you mind commenting the first three lines of code and then giving it a run? 
the first three lines were a fix for a local problem i was having.

**Comment by d3vsid-sudo** [comment]
I found the issue, the parent directory has to be named "sohei" or else it won't work

I have submitted a pull request for this, #11 kindly merge it.
Thanks @0x0elliot
