### ISSUE TITLE
check for CORS vulnerability and fix if it's possible

### ISSUE THREAD

**Issue by 0x0elliot** [GatewayDiscord/sohei#7]
[Here](https://portswigger.net/web-security/cors) is what CORS means. i believe the web app atm must be vulnerable to it since there was no origin header check performed. it is at low priority right now but still would be great to be taken care of as the web app develops itself.

**Comment by ujjwal-kr** [comment]
https://github.com/GatewayDiscord/sohei/pull/9

**Comment by 0x0elliot** [comment]
done!
